# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81e14f563780856ce536b1edf17b7f9856264855771b5492bab1bb8ed12e7734bee2c4ccb80c69beb966d3e2840bdc9f980096e39ae3f8738750e398ff06e1a6

test:
  secret_key_base: 8e355e30ac7b1b02ff7bf44a0664b4163dac6d659c03313b1fd0c541256c3295aa5269765cca03b972667ec63f8ada6e6814c82ed9706594df88edb8c464ebb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
